apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc-carsauction
spec:
  selector:
    matchLabels:
      app: notify-svc-carsauction
  template:
    metadata:
      labels:
        app: notify-svc-carsauction
    spec:
      containers:
      - name: notify-svc-carsauction
        image: 171717/notify-svc-carsauction
        imagePullPolicy: Always
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: notify-secret
                key: rabbitUn
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: notify-secret
                key: rabbitPw
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: notify-svc-carsauction
  ports:
  - port: 80
    targetPort: 80