apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc-carsauction
spec:
  selector:
    matchLabels:
      app: search-svc-carsauction
  template:
    metadata:
      labels:
        app: search-svc-carsauction
    spec:
      containers:
      - name: search-svc-carsauction
        image: 171717/search-svc-carsauction
        imagePullPolicy: Never
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            value: rabbit
          - name: RabbitMq__Password
            value: rabbit
          - name: ConnectionStrings__MongoDbConnection
            value: mongodb://root:mongopw@mongo-clusterip
          - name: AuctionServiceUrl
            value: http://auction-clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  type: ClusterIP
  selector:
    app: search-svc-carsauction
  ports:
  - port: 80
    targetPort: 80